// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeE9lzjD2kU0j6GHN0MEglk7H56CJtEyE',
    appId: '1:1066690467158:web:8206287d2d55a1c348f2f7',
    messagingSenderId: '1066690467158',
    projectId: 'cookbook-2023',
    authDomain: 'cookbook-2023.firebaseapp.com',
    storageBucket: 'cookbook-2023.appspot.com',
    measurementId: 'G-83PY79G060',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqMmPuVp-UfkV9J0pdgBzDYM6YE5Suglw',
    appId: '1:1066690467158:android:b0191a4369e00c8648f2f7',
    messagingSenderId: '1066690467158',
    projectId: 'cookbook-2023',
    storageBucket: 'cookbook-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG3nbRlblNK8CZbxFst8RnYeKBmhtkR4s',
    appId: '1:1066690467158:ios:5260a6c5d0a6a06748f2f7',
    messagingSenderId: '1066690467158',
    projectId: 'cookbook-2023',
    storageBucket: 'cookbook-2023.appspot.com',
    androidClientId: '1066690467158-dts9djet48t67lugc868bkui7t55npmg.apps.googleusercontent.com',
    iosClientId: '1066690467158-13t5so2flf3h5gps0ng5ttd2336vernj.apps.googleusercontent.com',
    iosBundleId: 'com.fyp.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG3nbRlblNK8CZbxFst8RnYeKBmhtkR4s',
    appId: '1:1066690467158:ios:20c471dac783c6b748f2f7',
    messagingSenderId: '1066690467158',
    projectId: 'cookbook-2023',
    storageBucket: 'cookbook-2023.appspot.com',
    androidClientId: '1066690467158-dts9djet48t67lugc868bkui7t55npmg.apps.googleusercontent.com',
    iosClientId: '1066690467158-svqai6bobhvlh62618mgom2l3m7i7dvt.apps.googleusercontent.com',
    iosBundleId: 'com.fyp.cookbook.RunnerTests',
  );
}
